### ISSUE TITLE
Which branch should I use?

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/workstation#2]
Hi all,

I tried to build the project on the master branch.
But it returned an error with:
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/10544528/65521396-c1338180-df1b-11e9-9690-c853657255fc.png">

I wonder if I should use another branch for building, or I didn't update the maven dependencies correctly?

Any advice will be greatly appreciated!

**Comment by krokicki** [comment]
The master branch is building successfully, as you can see on CircleCI (click the "PASSED" link on the main page). You can also try any of the release branches: https://github.com/JaneliaSciComp/workstation/releases

Judging from the error, you might be having a network issue connecting to our Maven repo. Make sure you can access https://nexus.janelia.org/repository/maven-releases/
