### ISSUE TITLE
Upgrade JHDF5 to version 19.04

### ISSUE THREAD

**Issue by mkitti** [JaneliaSciComp/workstation#23]
## New feature

Upgrade JHDF5 to version 19.04

## Proposal

A new version of JHDF5 is available at version 19.04.

The scijava-pom has integrated this version pending imminent release after testing. Several frameworks have already completed this upgrade including BigDataViewer.
https://github.com/scijava/pom-scijava/blob/9886b0ad01069adf9d294c54a65803ea19039115/pom.xml#L1678-L1679

https://github.com/scijava/pom-scijava/issues/181#issuecomment-1027297117

JaneliaSciComp currently has an active fork at https://github.com/JaneliaSciComp/jhdf5, and we are communicating those changes upstream to https://sissource.ethz.ch/sispub/jhdf5

## Usage scenario 

The HDF5 library is needed to read H5J. This will allow the use of the latest HDF5 features to do so, including performance upgrades.

## Suggest implementation 

A summary of needed modifications can be found here:
https://github.com/scijava/pom-scijava/issues/181#issuecomment-966066753

I would be happy to submit a pull request to this effect.

**Comment by krokicki** [comment]
@mkitti , we don't use HDF5 in this repo anymore. Someone implemented an H5J reader in the Workstation at some point, but it's long deprecated and should be removed.

**Comment by mkitti** [comment]
OK, I saw it in the Viewer3D pom.xml

https://github.com/JaneliaSciComp/workstation/blob/49276178571805b8c854ade24872ca8793872fcc/modules/Viewer3D/src/main/java/org/janelia/workstation/ffmpeg/H5JLoader.java#L5

It's good that I wrote the issue up before trying to actually change anything.
