### ISSUE TITLE
Broken link in docs/SamplePipeline.md

### ISSUE THREAD

**Issue by pnewstein** [JaneliaSciComp/workstation#43]
### Expected behavior and actual behavior

There is a broken link on the Sample Pipeline documentation. Perhaps it is pointing to a private github repo.

### Steps to reproduce the problem

1. Log out of github
1. go to https://github.com/JaneliaSciComp/workstation/blob/master/docs/SamplePipeline.md
1. Click on the link in Distortion Correction, Implementation: https://github.com/JaneliaSciComp/otsunah/tree/master/Distortion_correction
1. Get 404 page

**Comment by krokicki** [comment]
Thanks for reporting this, @pnewstein. We have made the repo public so you should be able to view it now.
