### ISSUE TITLE
wrong website

### ISSUE THREAD

**Issue by GG-yuki** [JaneliaSciComp/workstation#9]
The install link in the user guide
http://workstation.int.janelia.org/manual/install.html
go wrong.
Hope sb can fix the problem. thx

**Comment by GG-yuki** [comment]
does any body here？（cry）
It's an emengency

**Comment by krokicki** [comment]
Sorry @GG-yuki, we don't monitor the issues here and it is not a support forum. If you are at Janelia, you should contact the Help Desk with details about the issue you're experiencing. 

Please note that the Workstation is not available outside Janelia unless someone at your institution has deployed it. In that case, you should contact them with any issues. 

Best, Konrad
